### PR TITLE
Add Bram...

### PR DESCRIPTION
**Pull request by hoffmang9**
Kind of a hilarious omission actually

### CODE REVIEW

**Review by jack60612 — APPROVED** [review]
🤣

**Review by danieljperry — APPROVED** [review]
Kind of an important one.

**Review by Starttoaster — APPROVED** [review]

**Comment by Starttoaster** [comment]
I believe it wasn't in chialinks or electric-company at time of writing, which were the main two sources of truth I pulled from.

**Comment by hoffmang9** [comment]
No issue that it was missed. Bram just kind of started developing over there late last year. Don't sweat it. Just funny.

**Pull request merged**
